// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getCaptcha.proto

package getCaptcha

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetCaptcha service

type GetCaptchaService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getCaptchaService struct {
	c    client.Client
	name string
}

func NewGetCaptchaService(name string, c client.Client) GetCaptchaService {
	return &getCaptchaService{
		c:    c,
		name: name,
	}
}

func (c *getCaptchaService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetCaptcha.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetCaptcha service

type GetCaptchaHandler interface {
	Call(context.Context, *Request, *Response) error
}

func RegisterGetCaptchaHandler(s server.Server, hdlr GetCaptchaHandler, opts ...server.HandlerOption) error {
	type getCaptcha interface {
		Call(ctx context.Context, in *Request, out *Response) error
	}
	type GetCaptcha struct {
		getCaptcha
	}
	h := &getCaptchaHandler{hdlr}
	return s.Handle(s.NewHandler(&GetCaptcha{h}, opts...))
}

type getCaptchaHandler struct {
	GetCaptchaHandler
}

func (h *getCaptchaHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.GetCaptchaHandler.Call(ctx, in, out)
}
